In [4]:
from scipy.stats import binom
binom.pmf(3,16,(1/6))

0.2423137603371325

In [4]:
from scipy.stats import linregress
x=[34, 35, 39, 42, 43, 47]
y=[102, 109, 138, 148, 150, 158]
slope=round(linregress(x,y).slope,1)    #this is for finding the slope of the equation
intercept=round(linregress(x,y).intercept,1)    #This is for finding the intercept of the equation
print(slope)
print(intercept)
print(f'y= {intercept} + {slope}x')

4.5
-45.5
y= -45.5 + 4.5x


# Numpy lesson

In [3]:
import numpy as np

In [8]:
my_list=[1,2,3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [12]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Linear space returns number that are evenly spaced

In [21]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [22]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

### Generating identity matrix
Inside the function you are passing the number of rows and column, since in identity matrix the number of rows and columns is the same you will pass just a single value

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(7)

array([0.04629354, 0.22035407, 0.39756131, 0.36269745, 0.02797824,
       0.37376598, 0.01564733])

In [29]:
np.random.rand(30)   #It creates random numbers from 0 to 1

array([0.57401974, 0.67866919, 0.86604325, 0.19100275, 0.80358337,
       0.08797586, 0.00117144, 0.95124361, 0.22814724, 0.03005638,
       0.68222556, 0.53362661, 0.70647226, 0.4101877 , 0.81734234,
       0.9815824 , 0.26748446, 0.9770845 , 0.74141975, 0.54763001,
       0.83832947, 0.52046851, 0.05699741, 0.61038989, 0.42280188,
       0.15034375, 0.35651803, 0.17895748, 0.43111278, 0.4002808 ])

In [32]:
arra=np.arange(0,16)

In [33]:
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
arra.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
x=np.random.rand(36)

In [39]:
x

array([0.41932285, 0.09797417, 0.47201747, 0.14428625, 0.65610801,
       0.63973125, 0.28761403, 0.85503674, 0.05346878, 0.19286737,
       0.01980243, 0.64125531, 0.76081455, 0.44761428, 0.70383708,
       0.75168432, 0.28842622, 0.45665624, 0.16668382, 0.67848743,
       0.15850631, 0.90342476, 0.18494145, 0.87196443, 0.72018779,
       0.05069276, 0.13728419, 0.59731826, 0.38963997, 0.57222935,
       0.73559478, 0.06241324, 0.69912716, 0.27519169, 0.85602262,
       0.76027896])

In [40]:
x.reshape(6,6) #reshape function just arrange into a matrix

array([[0.41932285, 0.09797417, 0.47201747, 0.14428625, 0.65610801,
        0.63973125],
       [0.28761403, 0.85503674, 0.05346878, 0.19286737, 0.01980243,
        0.64125531],
       [0.76081455, 0.44761428, 0.70383708, 0.75168432, 0.28842622,
        0.45665624],
       [0.16668382, 0.67848743, 0.15850631, 0.90342476, 0.18494145,
        0.87196443],
       [0.72018779, 0.05069276, 0.13728419, 0.59731826, 0.38963997,
        0.57222935],
       [0.73559478, 0.06241324, 0.69912716, 0.27519169, 0.85602262,
        0.76027896]])

## Indedxing arrays

In [7]:
arr=np.arange(0,30,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
arr[3]

9

In [48]:
arr[3:8]

array([ 9, 12, 15, 18, 21])

In [49]:
arr[:6]

array([ 0,  3,  6,  9, 12, 15])

In [50]:
arr[6:]

array([18, 21, 24, 27])

#### Always use array.copy() to avoid ruinung the original array

In [9]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
arr_sub=arr[:6]
print(arr_sub)

[ 0  3  6  9 12 15]


In [11]:
arr_sub[:]=10

In [12]:
arr_sub

array([10, 10, 10, 10, 10, 10])

In [13]:
arr

array([10, 10, 10, 10, 10, 10, 18, 21, 24, 27])

### Always use array.copy() to avoid ruinung the original array

In [24]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [26]:
arr_sub1=arr.copy()
arr_sub1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [27]:
arr_sub1[:]=100

In [28]:
arr_sub1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr  #so copying the array does not affect the original array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [43]:
arr_2d=[[34,45,98],[39,72,40],[23,67,83]]
np.array(arr_2d)

array([[34, 45, 98],
       [39, 72, 40],
       [23, 67, 83]])

In [44]:
arr_2d[1][2]

40

In [52]:
arr_2d[:2][1]

[39, 72, 40]

In [53]:
arr_3=np.arange(20,40,3)

In [54]:
arr_3

array([20, 23, 26, 29, 32, 35, 38])

In [62]:
bool_arr = arr_3 > 25
bool_arr

array([False, False,  True,  True,  True,  True,  True])

In [63]:
arr_3[bool_arr]

array([26, 29, 32, 35, 38])

In [64]:
arr_3[arr_3>26]

array([29, 32, 35, 38])

In [6]:
arra=np.arange(0,100,2).reshape(10,5)

In [7]:
arra

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [9]:
arra[3:6,1:4]

array([[32, 34, 36],
       [42, 44, 46],
       [52, 54, 56]])

In [11]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [2]:
import numpy as np
import pandas as pd

In [8]:
label = ['a','b','c']
my_array = [1,2,3]
arr=np.array(my_array)
d={'a':1, 'b':2, 'c':3}

#creating a series using panda
pd.Series(data=my_array,index=label)

a    1
b    2
c    3
dtype: int64

In [9]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [10]:
pd.Series(arr,labe)

a    1
b    2
c    3
dtype: int32

In [13]:
ser1=pd.Series([1,2,3,4], ['USA','GERMANY', 'USSR', 'JAPAN'])
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [15]:
ser2=pd.Series([1,2,5,4], ['USA','GERMANY', 'ITALY', 'JAPAN'])
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [16]:
ser1['GERMANY']

2

In [17]:
ser1['USA'] + ser2['USA']

2

### Data frames

In [8]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [12]:
df = pd.DataFrame(randn(5,4),['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

W         X         Y         Z
A  0.147027 -0.479448  0.558769  1.024810
B -0.925874  1.862864 -1.133817  0.610478
C  0.386030  2.084019 -0.376519  0.230336
D  0.681209  1.035125 -0.031160  1.939932
E -1.005187 -0.741790  0.187125 -0.732845

In [13]:
df['Y']

A    0.558769
B   -1.133817
C   -0.376519
D   -0.031160
E    0.187125
Name: Y, dtype: float64

In [15]:
type(df['Y'])

pandas.core.series.Series

In [16]:
type(df) #Dataframes are composed of series

pandas.core.frame.DataFrame

In [18]:
df[['W','Z']]

W         Z
A  0.147027  1.024810
B -0.925874  0.610478
C  0.386030  0.230336
D  0.681209  1.939932
E -1.005187 -0.732845

In [21]:
df['new'] = df['Z'] + df['Y']
df

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339
C  0.386030  2.084019 -0.376519  0.230336 -0.146182
D  0.681209  1.035125 -0.031160  1.939932  1.908772
E -1.005187 -0.741790  0.187125 -0.732845 -0.545721

In [24]:
df.drop('Y',axis=1) #removing columns

W         X         Z       new
A  0.147027 -0.479448  1.024810  1.583580
B -0.925874  1.862864  0.610478 -0.523339
C  0.386030  2.084019  0.230336 -0.146182
D  0.681209  1.035125  1.939932  1.908772
E -1.005187 -0.741790 -0.732845 -0.545721

In [25]:
df.drop('D') #The axis is 0 for rows and 1 for columns and it is 0 by default

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339
C  0.386030  2.084019 -0.376519  0.230336 -0.146182
E -1.005187 -0.741790  0.187125 -0.732845 -0.545721

In [26]:
df # the values will not be removed permanent untill you specify with inplace TRUE

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339
C  0.386030  2.084019 -0.376519  0.230336 -0.146182
D  0.681209  1.035125 -0.031160  1.939932  1.908772
E -1.005187 -0.741790  0.187125 -0.732845 -0.545721

In [28]:
df.loc[['A','B']]  #If you want to get the rows use loc

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339

In [34]:
df.iloc[[0,1]]   #Or you can use iloc if you wanna pass the index of the row

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339

In [36]:
df.loc['B','new']

-0.5233392540453254

In [41]:
df.loc[['A','B'], ['X','Y']]

X         Y
A -0.479448  0.558769
B  1.862864 -1.133817

In [42]:
df

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339
C  0.386030  2.084019 -0.376519  0.230336 -0.146182
D  0.681209  1.035125 -0.031160  1.939932  1.908772
E -1.005187 -0.741790  0.187125 -0.732845 -0.545721

In [43]:
df[df>0]

W         X         Y         Z       new
A  0.147027       NaN  0.558769  1.024810  1.583580
B       NaN  1.862864       NaN  0.610478       NaN
C  0.386030  2.084019       NaN  0.230336       NaN
D  0.681209  1.035125       NaN  1.939932  1.908772
E       NaN       NaN  0.187125       NaN       NaN

In [45]:
df > 0

W      X      Y      Z    new
A   True  False   True   True   True
B  False   True  False   True  False
C   True   True  False   True  False
D   True   True  False   True   True
E  False  False   True  False  False

In [46]:
df

W         X         Y         Z       new
A  0.147027 -0.479448  0.558769  1.024810  1.583580
B -0.925874  1.862864 -1.133817  0.610478 -0.523339
C  0.386030  2.084019 -0.376519  0.230336 -0.146182
D  0.681209  1.035125 -0.031160  1.939932  1.908772
E -1.005187 -0.741790  0.187125 -0.732845 -0.545721

In [59]:
df[df['Z']>0][['Y','X']]

Y         X
A  0.558769 -0.479448
B -1.133817  1.862864
C -0.376519  2.084019
D -0.031160  1.035125

In [62]:
boole=df['Z']>0
result=df[boole]
val=['Y', 'X']
result[val]

Y         X
A  0.558769 -0.479448
B -1.133817  1.862864
C -0.376519  2.084019
D -0.031160  1.035125

In [70]:
#index levels
outside=['G1', 'G1', 'G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
heir_index=list(zip(outside,inside))
heir_index=pd.MultiIndex.from_tuples(heir_index)

In [72]:
df=pd.DataFrame(randn(6,2),heir_index,['A', 'B'])

In [73]:
df

A         B
G1 1 -1.972605 -0.866885
   2  0.720788 -1.223082
   3  1.606780 -1.115710
G2 1 -1.385379 -1.329660
   2  0.041460 -0.411055
   3 -0.771329  0.110477

In [85]:
df.loc['G1']

A         B
1 -1.972605 -0.866885
2  0.720788 -1.223082
3  1.606780 -1.115710

In [86]:
df.index.names=['Group','number']

In [87]:
df

A         B
Group number                    
G1    1      -1.972605 -0.866885
      2       0.720788 -1.223082
      3       1.606780 -1.115710
G2    1      -1.385379 -1.329660
      2       0.041460 -0.411055
      3      -0.771329  0.110477

In [113]:
df.loc['G1',['B']].loc[3]


B   -1.11571
Name: 3, dtype: float64

In [114]:
df.loc['G2'].loc[2]


A    0.041460
B   -0.411055
Name: 2, dtype: float64

In [116]:
df.xs(2,level='number')  #xs-means it will take the values of number one in both groups

A         B
Group                    
G1     0.720788 -1.223082
G2     0.041460 -0.411055